import StyleDictionary from 'style-dictionary';
import type { Config, TransformedToken } from 'style-dictionary/types';
import { fileHeader } from 'style-dictionary/utils';

// ─── CUSTOM FORMAT: typed TypeScript theme object ─────────────────────────────
// Produces: export const theme = { norauto: { primary: { "10": "..." } } } as const

StyleDictionary.registerFormat({
  name: 'typescript/theme-object',
  format: async ({ dictionary, file, options }) => {
    const { usesDtcg } = options;
    const header = await fileHeader({ file });

    function buildNestedObject(
      tokens: TransformedToken[]
    ): Record<string, unknown> {
      const result: Record<string, unknown> = {};
      for (const token of tokens) {
        const parts = token.path;
        let current = result;
        for (let i = 0; i < parts.length - 1; i++) {
          if (!current[parts[i]]) current[parts[i]] = {};
          current = current[parts[i]] as Record<string, unknown>;
        }
        current[parts[parts.length - 1]] = usesDtcg ? token.$value : token.value;
      }
      return result;
    }

    const nested = buildNestedObject(dictionary.allTokens);
    const jsonBody = JSON.stringify(nested, null, 2);

    return (
      header +
      `// Auto-generated by Style Dictionary — do not edit directly.\n` +
      `// Edit tokens/source/**/*.json instead.\n\n` +
      `export const theme = ${jsonBody} as const;\n\n` +
      `export type Theme = typeof theme;\n`
    );
  },
});

// ─── CUSTOM TRANSFORM: strip mode prefix for semantic tokens ──────────────────
// Tokens under light/dark/contrast get the mode prefix removed from the CSS
// variable name. Path ['light','surface','surface'] → name 'surface-surface'
// Primitive tokens (no mode prefix) are passed through unchanged.

StyleDictionary.registerTransform({
  name: 'name/strip-mode',
  type: 'name',
  // Mirrors name/kebab: join path with '-' and prepend the platform prefix.
  // For mode-prefixed semantic tokens, strip the first path component (light/dark/contrast)
  // so the CSS var name does NOT include the mode.
  transform: (token: TransformedToken, options): string => {
    const MODES = ['light', 'dark', 'contrast'];
    const path = MODES.includes(token.path[0]) ? token.path.slice(1) : token.path;
    const prefix = (options as Record<string, unknown>)?.prefix as string | undefined;
    return [prefix, ...path].filter(Boolean).join('-');
  },
});

// ─── MAIN CONFIGURATION ───────────────────────────────────────────────────────

const MODES = ['light', 'dark', 'contrast'] as const;

const config: Config = {
  usesDtcg: true,
  source: ['tokens/source/**/*.json'],

  platforms: {
    // ── Primitive tokens → variables.css (:root) + theme.ts ─────────────────
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      prefix: 'ds',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          // Exclude mode-prefixed semantic tokens — handled by css-semantic below
          filter: (t: TransformedToken) => !MODES.includes(t.path[0] as typeof MODES[number]),
          options: {
            outputReferences: false,
            selector: ':root',
          },
        },
      ],
    },

    // ── Semantic tokens → semantic-{mode}.css with appropriate selectors ─────
    // Uses name/strip-mode to drop the light/dark/contrast prefix from var names.
    // :root for light, [data-theme="dark"] for dark, [data-theme="contrast"] for contrast.
    'css-semantic': {
      transforms: ['attribute/cti', 'name/strip-mode', 'color/css', 'size/rem'],
      buildPath: 'tokens/build/',
      prefix: 'ds',
      files: [
        {
          destination: 'semantic-light.css',
          format: 'css/variables',
          filter: (t: TransformedToken) => t.path[0] === 'light',
          options: { outputReferences: false, selector: ':root' },
        },
        {
          destination: 'semantic-dark.css',
          format: 'css/variables',
          filter: (t: TransformedToken) => t.path[0] === 'dark',
          options: { outputReferences: false, selector: '[data-theme="dark"]' },
        },
        {
          destination: 'semantic-contrast.css',
          format: 'css/variables',
          filter: (t: TransformedToken) => t.path[0] === 'contrast',
          options: { outputReferences: false, selector: '[data-theme="contrast"]' },
        },
      ],
    },

    // ── TypeScript theme object ───────────────────────────────────────────────
    ts: {
      transformGroup: 'js',
      buildPath: 'tokens/build/',
      files: [
        {
          destination: 'theme.ts',
          format: 'typescript/theme-object',
          options: { outputReferences: false },
        },
      ],
    },
  },
};

// ─── BUILD ────────────────────────────────────────────────────────────────────

const sd = new StyleDictionary(config);
await sd.buildAllPlatforms();
