import StyleDictionary from 'style-dictionary';
import type { Config, TransformedToken } from 'style-dictionary/types';
import { fileHeader } from 'style-dictionary/utils';

// ---------------------------------------------------------------------------
// Custom format: outputs a typed TypeScript ESM module.
// Produces: export const theme = { color: { primary: "..." }, ... } as const
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: 'typescript/theme-object',
  format: async ({ dictionary, file, options }) => {
    const { usesDtcg } = options;
    const header = await fileHeader({ file });

    function buildNestedObject(
      tokens: TransformedToken[]
    ): Record<string, unknown> {
      const result: Record<string, unknown> = {};
      for (const token of tokens) {
        const parts = token.path;
        let current = result;
        for (let i = 0; i < parts.length - 1; i++) {
          if (!current[parts[i]]) current[parts[i]] = {};
          current = current[parts[i]] as Record<string, unknown>;
        }
        current[parts[parts.length - 1]] = usesDtcg ? token.$value : token.value;
      }
      return result;
    }

    const nested = buildNestedObject(dictionary.allTokens);
    const jsonBody = JSON.stringify(nested, null, 2);

    return (
      header +
      `// Auto-generated by Style Dictionary — do not edit directly.\n` +
      `// Edit tokens/source/*.json instead.\n\n` +
      `export const theme = ${jsonBody} as const;\n\n` +
      `export type Theme = typeof theme;\n`
    );
  },
});

// ---------------------------------------------------------------------------
// Main configuration
// ---------------------------------------------------------------------------
const config: Config = {
  usesDtcg: true,
  source: ['tokens/source/**/*.json'],

  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      prefix: 'ds',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: false,
            selector: ':root',
          },
        },
      ],
    },

    ts: {
      transformGroup: 'js',
      buildPath: 'tokens/build/',
      files: [
        {
          destination: 'theme.ts',
          format: 'typescript/theme-object',
          options: {
            outputReferences: false,
          },
        },
      ],
    },
  },
};

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------
const sd = new StyleDictionary(config);
await sd.buildAllPlatforms();
