import StyleDictionary from 'style-dictionary';
import type { Config, TransformedToken } from 'style-dictionary/types';
import { fileHeader } from 'style-dictionary/utils';

// ─── CUSTOM FORMAT: typed TypeScript theme object ─────────────────────────────
// Produces: export const theme = { blue: { "blue-700": "..." } } as const

StyleDictionary.registerFormat({
  name: 'typescript/theme-object',
  format: async ({ dictionary, file, options }) => {
    const { usesDtcg } = options;
    const header = await fileHeader({ file });

    function buildNestedObject(
      tokens: TransformedToken[]
    ): Record<string, unknown> {
      const result: Record<string, unknown> = {};
      for (const token of tokens) {
        const parts = token.path;
        let current = result;
        for (let i = 0; i < parts.length - 1; i++) {
          if (!current[parts[i]]) current[parts[i]] = {};
          current = current[parts[i]] as Record<string, unknown>;
        }
        current[parts[parts.length - 1]] = usesDtcg ? token.$value : token.value;
      }
      return result;
    }

    const nested = buildNestedObject(dictionary.allTokens);
    const jsonBody = JSON.stringify(nested, null, 2);

    return (
      header +
      `// Auto-generated by Style Dictionary — do not edit directly.\n` +
      `// Edit tokens/source/**/*.json instead.\n\n` +
      `export const theme = ${jsonBody} as const;\n\n` +
      `export type Theme = typeof theme;\n`
    );
  },
});

// ─── HELPERS ─────────────────────────────────────────────────────────────────

const isPrimitive = (t: TransformedToken) =>
  !t.filePath.includes('semantic/');

const isSemantic = (t: TransformedToken) =>
  t.filePath.includes('semantic/');

// ─── MAIN CONFIGURATION ───────────────────────────────────────────────────────

const config: Config = {
  usesDtcg: true,
  source: ['tokens/source/**/*.json'],
  // Broken references exist in non-norauto brand files (missing alert.* and decorative.*
  // primitive scales). Treat them as warnings so the build completes; fix when those
  // primitives are added.
  log: {
    verbosity: 'default',
    warnings: 'warn',
    errors: { brokenReferences: 'console' },
  },

  platforms: {
    // ── Primitive tokens → variables.css (:root) ─────────────────────────────
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      prefix: 'ds',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          filter: isPrimitive,
          options: {
            outputReferences: false,
            selector: ':root',
          },
        },
      ],
    },

    // ── Semantic tokens → semantic.css (:root) ────────────────────────────────
    'css-semantic': {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      prefix: 'ds',
      files: [
        {
          destination: 'semantic.css',
          format: 'css/variables',
          filter: isSemantic,
          options: {
            outputReferences: false,
            selector: ':root',
          },
        },
      ],
    },

    // ── TypeScript theme object ───────────────────────────────────────────────
    ts: {
      transformGroup: 'js',
      buildPath: 'tokens/build/',
      files: [
        {
          destination: 'theme.ts',
          format: 'typescript/theme-object',
          options: { outputReferences: false },
        },
      ],
    },
  },
};

// ─── BUILD ────────────────────────────────────────────────────────────────────

const sd = new StyleDictionary(config);
await sd.buildAllPlatforms();
